path: ./
sub_path: meshes
draw: false
isSave: false
savePath: ./result/test_e36b21e2
continueFlag: true
adjust_crown: 1
registAlph: 0.8
tpsAlpha: 0.01
normalSize: 0.5
cement_gap: 0.08
minimal_gap: 0.04
height_of_minimal_gap: 1.0
height_of_minimal_gap2: 0.1
lastSubmehs_tps_num: 500
lastSubmehs_tps_dis: 0.55
lastSubmehs_tps_ignoreDis: 0.1
stitching_width: 0.07
outer_pre_lift_dis: 0.2
boundaryTPS_range: 1.0
thickness: 0.6
boundary_protect_range_offset: 0
isDraw: false
ad_gap: 0.03
ignoreBoundDis: 0.01
fixBoundDis: 0.01
insertExport: 0.01
lastDis: 0.01
alph: 0.02
