
name: Pull Repository

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'input source branch'
        required: true
        default: 'main'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.source_branch }}
          repository: soonsolidwensheng/AI_Crown.git
          token: ${{ secrets.ACCESS_TOKEN }}  
          path: source
          
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          path: target
          token: ${{ secrets.ACCESS_TOKEN }}  

      - name: Sync files with exclusions
        run: |
          sudo rsync -av --delete --exclude='Dockerfile' --exclude='.*'    source/ target/   

      - name: Commit and push changes
        run: |
          cd target
          git checkout -b  ${{ github.event.inputs.source_branch }}
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-sync from source repo"
          git push origin ${{ github.event.inputs.source_branch }} --force
