
name: Pull Repository

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'input source branch'
        required: true
        default: 'main'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.source_branch }}
          repository: SprintRay-Software/AI_Inlay_Generation.git
          token: ${{ secrets.SOURCE_ACCESS_TOKEN }}  
          path: source
          
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          path: target
          token: ${{ secrets.TARGET_ACCESS_TOKEN }}  
          fetch-depth: 0  # 获取完整提交历史
          
      - name: Get branch name
        id: get-branch
        run: |
          # 如果是pull_request事件，使用GITHUB_HEAD_REF获取源分支
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "branch_name=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          else
            echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          fi
          
      - name: Sync files with exclusions
        run: |
          sudo rsync -av --delete --exclude='Dockerfile' --exclude='.*'    source/ target/   

      - name: Commit and push changes
        run: |
          cd target
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-pull from source repo"
          # 强制推送更新
          git push origin HEAD:${{ steps.get-branch.outputs.branch_name }} --force
