name: Sync with rsync
on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: '输入要运行的分支名'
        required: true
        default: 'dev'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出源项目代码
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: source-dir  # 指定检出目录

      # 2. 克隆目标仓库（需认证）
      - name: Clone target repo
        run: |
          git clone https://${{ github.actor }}:${{ secrets.ACCESS_TOKEN }}@github.com/soonsolidwensheng/AI_Crown.git target-dir
          
      # 3. 使用 rsync 同步文件（排除示例）
      - name: Sync files with rsync
        run: |
          rsync -av --delete \
            --exclude='Dockerfile' \          # 排除
            source-dir/ target-dir/      # 注意结尾斜杠表示同步目录内容

      # 4. 提交并推送更改
      - name: Commit and push changes
        run: |
          cd target-dir
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Auto-sync from source repo"
          git push origin ${{ github.event.inputs.target_branch }}
